gettext: fix for low-version recipe
Make gettext-native in 0.16.1 recipe provides virtual/gettext-native like
what gettext-native in 0.19.6 recipe does. Otherwise we would fail to start
to do a world build if gettext and gettext-native are set to the low version.
Error message is like below.

  ERROR: Multiple versions of gettext-native are due to be built

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>