elfutils: fix the num passed to memset in ar.c
Following build error will appear on Fedora18+:
ar.c: In function 'do_oper_delete':
ar.c:918:31: error: argument to 'sizeof' in 'memset' call is the same expression as the destination; did you mean to dereference it? [-Werror=sizeof-pointer-memaccess]
   memset (found, '\0', sizeof (found));

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit 5cc3b4fe09cfa2b3e67568a9c2494c198a5292af)
Signed-off-by: Andreas Oberritter <obi@opendreambox.org>