xtrans: Fix multilib .pc file conflict
Error: Transaction check error:
  file /usr/share/pkgconfig/xtrans.pc from install of lib32-xtrans-dev-1:1.3.5-r0.core2_32 conflicts with file from package xtrans-dev-1:1.3.5-r0.core2_64

[YOCTO #12511]

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>