oeqa: bbtests.BitbakeTests.test_image_manifest: use just isfile() instead of islink()
* with [YOCTO #12937] changes the manifest is hardlink not symlink

* fixes:
  2023-11-16 00:16:33,967 - oe-selftest - INFO - test_image_manifest (bbtests.BitbakeTests.test_image_manifest)
  2023-11-16 00:19:05,060 - oe-selftest - INFO -  ... FAIL
  2023-11-16 00:19:05,060 - oe-selftest - INFO - Traceback (most recent call last):
    File "/OE/build/poky/meta/lib/oeqa/selftest/cases/bbtests.py", line 139, in test_image_manifest
      self.assertTrue(os.path.islink(manifest), msg="No manifest file created for image. It should have been created in %s" % manifest)
  AssertionError: False is not true : No manifest file created for image. It should have been created in /OE/build/poky/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.rootfs--1.0-r0-20110405230000.manifest

[YOCTO #12937]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>