apt: Fix do_compile error when enable ccache
Fixed:
apt-pkg/libapt-pkg.so.5.0.2: undefined reference to `ZSTD_endStream'
collect2: error: ld returned 1 exit status

This is because ccache-native depends on zstd-native which makes apt wronly
find it. Disable zstd for apt to fix the problem.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>