tcl: extend to nativesdk
Fixed:
$ bitbake nativesdk-expect
ERROR: Nothing PROVIDES 'nativesdk-tcl' (but virtual:nativesdk:expect_5.45.bb DEPENDS on or otherwise requires it). Close matches:
[snip]

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>