btrfs-tools: only target requires udev
The native doesn't have to depend on udev, fixed:

$ bitbake btrfs-tools-native

ERROR: Nothing PROVIDES 'udev-native' (but virtual:native:btrfs-tools_4.8.5.bb DEPENDS on or otherwise requires it). Close matches:
[snip]

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>