meta-skeleton: useradd-dep: add example of recipe using useradd and group created in other recipe
* maybe this would be better in meta-selftest, I can move it there
  once we agree how this is supposed to work

* https://www.openembedded.org/pipermail/bitbake-devel/2018-March/009256.html
  says that RDEPENDS_${PN} should be enough, but in my testing we need
  built time dependency as well for groups to exist early enough

* and unfortunately even with the "useradd dependency" in DEPENDS is see
  very rare failures (in dunfell but I haven't found any changes in this area
  in master) when useradd-dep and useradd-example are reused from sstate.

  In these cases I've noticed that useradd-dep.do_package_setscene is running before useradd-example.do_package_setscene:

  NOTE: Running setscene task 268 of 3783 (useradd-dep.bb:do_package_write_ipk_setscene)
  NOTE: Running setscene task 269 of 3783 (useradd-dep.bb:do_populate_lic_setscene)
  NOTE: useradd-dep-1.0-r1: task do_package_write_ipk_setscene: Started
  NOTE: useradd-dep-1.0-r1: task do_populate_lic_setscene: Started
  NOTE: useradd-dep-1.0-r1: task do_package_write_ipk_setscene: Succeeded
  NOTE: Running setscene task 279 of 3783 (useradd-dep.bb:do_packagedata_setscene)
  NOTE: useradd-dep-1.0-r1: task do_populate_lic_setscene: Succeeded
  NOTE: useradd-dep-1.0-r1: task do_packagedata_setscene: Started
  NOTE: useradd-dep-1.0-r1: task do_packagedata_setscene: Succeeded
  NOTE: Running setscene task 3336 of 3783 (useradd-dep.bb:do_package_setscene)
  NOTE: Running setscene task 3337 of 3783 (useradd-dep.bb:do_populate_sysroot_setscene)
  NOTE: useradd-dep-1.0-r1: task do_package_setscene: Started
  NOTE: useradd-dep-1.0-r1: task do_populate_sysroot_setscene: Started
  ERROR: useradd-dep-1.0-r1 do_package_setscene: useradd-dep: useradd command did not succeed.
  ERROR: useradd-dep-1.0-r1 do_package_setscene: Error executing a python function in exec_python_func() autogenerated:
  ...
  Exception: bb.process.ExecutionError: Execution of 'useradd-dep/1.0-r1/temp/run.useradd_sysroot.8980' failed with exit code 1:
    useradd-dep/1.0-r1/recipe-sysroot-native/usr/sbin/useradd
    Running useradd commands...
    useradd: Warning: missing or non-executable shell '/bin/bash'
    useradd: group 'group1' does not exist
    WARNING: exit code 1 from a shell command.
  ...
  WARNING: Setscene task (useradd-dep.bb:do_package_setscene) failed with exit code '1' - real task will be run instead

  NOTE: Running setscene task 3347 of 3783 (useradd-example.bb:do_packagedata_setscene)
  NOTE: Running setscene task 3348 of 3783 (useradd-example.bb:do_populate_sysroot_setscene)
  NOTE: recipe useradd-example-1.0-r1: task do_packagedata_setscene: Started
  NOTE: recipe useradd-example-1.0-r1: task do_populate_sysroot_setscene: Started
  NOTE: recipe useradd-example-1.0-r1: task do_packagedata_setscene: Succeeded
  NOTE: Running setscene task 3358 of 3783 (useradd-example.bb:do_package_setscene)
  NOTE: recipe useradd-example-1.0-r1: task do_populate_sysroot_setscene: Succeeded
  NOTE: recipe useradd-example-1.0-r1: task do_package_setscene: Started
  NOTE: recipe useradd-example-1.0-r1: task do_package_setscene: Succeeded

  and then the real task works fine.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>