selftest/recipetool.py: set srcrev for recipetool create
The srcrev would default to master when not set, which may cause erorrs
when the source is changed.

Fixed:
======================================================================
FAIL: test_recipetool_create_git (oeqa.selftest.recipetool.RecipetoolTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-oe-selftest/build/meta/lib/oeqa/utils/decorators.py", line 106, in wrapped_f
    return func(*args, **kwargs)
  File "/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-oe-selftest/build/meta/lib/oeqa/selftest/recipetool.py", line 402, in test_recipetool_create_git
    self._test_recipe_contents(recipefile, checkvars, inherits)
  File "/home/pokybuild/yocto-autobuilder/yocto-worker/nightly-oe-selftest/build/meta/lib/oeqa/selftest/devtool.py", line 25, in _test_recipe_contents
    self.assertEqual(value, needvalue, 'values for %s do not match' % var)
AssertionError: 'Unknown LGPLv2.1' != 'LGPLv2.1' : values for LICENSE do not match

The rev=9f7cf8895ae2d39c465c04cc78e918c157420269 is taken from master
branch. It was failed because libmatchbox's master branch has added a
COPYING.MIT, and the testcase only checks COPYING.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>