connman: Fix PPTP VPN plugin QA issue
This error was seen when building ConnMan. Fixed by not
building ConnMan pptp plugin with module versioning info.

ERROR: QA Issue: non -dev/-dbg/-nativesdk package contains symlink .so: connman-plugin-vpn-pptp path '/work/core2-32-oe-linux/connman/1.24+gitAUTOINC+42779cd63c-r20/packages-split/connman-plugin-vpn-pptp/usr/lib/connman/scripts/libppp-plugin.so' [dev-so]
ERROR: QA run found fatal errors. Please consider fixing them.
ERROR: Function failed: do_package_qa

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
(cherry picked from commit d2328d6aa52fd4f0b47ae3292ae6ae07301bf9d0)
Signed-off-by: Andreas Oberritter <obi@opendreambox.org>