alsa-utils: fix FILES of alsa-utils-alsactl
Fix to use ${nonarch_base_libdir}/udev/rules.d instead of */udev/rules.d
to avoid the following QA warning.

ERROR: QA Issue: alsa-utils: Files/directories were installed but not shipped
  /usr/lib/udev
  /usr/lib/udev/rules.d
  /usr/lib/udev/rules.d/90-alsa-restore.rules [installed-vs-shipped]

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>