multilib.bbclass: update DEFAULTTUNE for image recipe
Fixed:
MACHINE = "qemux86-64"
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "x86"

$ bitbake -e lib32-core-image-minimal | grep ^TUNE_ARCH=
TUNE_ARCH="x86_64"

This is incorrect, it should be i686 (or other 32 bit tunes), this makes
we can't conditionlly install some packages, for example, the recipe-A
sets:
COMPATIBLE_HOST = "x86_64.*-linux"

Then it only can be installed when TARGET_ARCH is x86_64:
IMAGE_INSTALL_x86-64 += "package-A"

But it would be error when "bitbake lib32-core-image-minimal":
ERROR: lib32-recipe-A was skipped: incompatible with host i686-pokymllib32-linux (not in COMPATIBLE_HOST)

This is because TARGET_ARCH is not updated to "i686" when multilib, this
patch can fix the problem.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>