elfutils: Fix size passed to snprintf for invalid sh_name case
Following build error will appear on Fedora18.
nm.c: In function 'show_symbols_sysv':
nm.c:756:27: error: argument to 'sizeof' in 'snprintf' call is the same expression as the destination; did you mean to provide an explicit length? [-Werror=sizeof-pointer-memaccess]
    snprintf (name, sizeof name, "[invalid sh_name %#" PRIx32 "]",
                           ^

Signed-off-by: Zhenhua Luo <zhenhua.luo@freescale.com>
Signed-off-by: Saul Wold <sgw@linux.intel.com>
(cherry picked from commit 61010972284cc53cfc7958a9f6422e3fe74fcc0e)
Signed-off-by: Andreas Oberritter <obi@opendreambox.org>