sanity.bbclass: Update required gcc version to v7.5
qemu-native 6.1.0 requires at least gcc v7.5:
ERROR: You need at least GCC v7.5 or Clang v6.0 (or XCode Clang v10.0)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>