core-image-minimal-initramfs: set QB_DEFAULT_FSTYPE
Fixed:
MACHINE = "qemux86"
$ bitbake core-image-minimal-initramfs
$ runqemu qemux86 nographic
[snip]
Exception: Failed to find rootfs: tmp/deploy/images/qemux86/core-image-minimal-initramfs-qemux86-20170224082533*.ext4 or tmp/deploy/images/qemux86/core-image-minimal-initramfs-qemux86*.ext4
[snip]

This is because core-image-minimal-initramfs doesn't generate ext4 image which
is the default value or QB_DEFAULT_FSTYPE, it only generates cpio.gz.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>