multilib_header.bbclass: Do not install the stubs for non-multilib case
We mark certain headers which are not usable in multilib case through
this function, this however is a unnessary indirection when building
distros without multilib feature. Additionally it also addresses a case
where we compile baremetal software e.g. bootloaders or BPF binaries
e.g. which are a different target effectively but can be built using
same toolchain with some flags. This does not work when we always
install the stubs since the stubs require a fixed wordsize definition
and that may not be true for the BPF cases e.g. it will work fine when
multilib is enabled since that would have provided the headers it needed
say for 32bit multilib. Currently they go missing for a non-multilib
case and we end up with errors like

recipe-sysroot/usr/include/bits/long-double.h:23:10: fatal error: 'bits/long-double-32.h' file
not found
| #include <bits/long-double-32.h>

Therefore lets install these stubs only when using
multilib in distro

Signed-off-by: Khem Raj <raj.khem@gmail.com>