waffle: The surfaceless-egl and gbm requires opengl
Fixed when opengl is not in DISTRO_FEATURES:
ERROR: Nothing PROVIDES 'virtual/libgbm' (but /path/to/waffle/waffle_1.7.0.bb DEPENDS on or otherwise requires it)

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>